DROP TABLE IF EXISTS CIES_TRN_TASK_INFO;
DROP TABLE IF EXISTS CIES_TRN_REPO_INFO;
DROP TABLE IF EXISTS CIES_ENT_CUS_INFO;

CREATE TABLE CIES_ENT_CUS_INFO (
    CUS_ID VARCHAR(10) PRIMARY KEY,
    CUS_PRM_ACT VARCHAR(12) NOT NULL,
    CIES_FLAG VARCHAR(10) NOT NULL,
    CUS_EN_NAME VARCHAR(140) NOT NULL,
    CUS_CN_NAME VARCHAR(140) NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATE_USER VARCHAR(10) NOT NULL,
    UPDATE_TIME DATETIME NOT NULL,
    UPDATE_USER VARCHAR(10) NOT NULL
);

CREATE TABLE CIES_TRN_REPO_INFO (
    TRAN_ID VARCHAR(18) PRIMARY KEY,
    CUS_ID VARCHAR(10) NOT NULL,
    STATEMENT_ID VARCHAR(40) NOT NULL,
    TRAN_TYPE VARCHAR(3) NOT NULL,
    TRAN_STATUS VARCHAR(3) NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATE_USER VARCHAR(10) NOT NULL,
    UPDATE_TIME DATETIME NOT NULL,
    UPDATE_USER VARCHAR(10) NOT NULL,
    CONSTRAINT FK_REPO_CUSTOMER FOREIGN KEY (CUS_ID)
        REFERENCES CIES_ENT_CUS_INFO (CUS_ID)
);

CREATE TABLE CIES_TRN_TASK_INFO (
    TASK_ID VARCHAR(18) PRIMARY KEY,
    REF_ID VARCHAR(18) NOT NULL,
    TASK_STATUS VARCHAR(3) NOT NULL,
    TASK_REMARK VARCHAR(50),
    MAKER_ID VARCHAR(10),
    CHECKER_ID VARCHAR(10),
    CREATE_TIME DATETIME NOT NULL,
    UPDATE_TIME DATETIME NOT NULL,
    CONSTRAINT FK_TASK_REPO FOREIGN KEY (REF_ID)
        REFERENCES CIES_TRN_REPO_INFO (TRAN_ID)
);

CREATE INDEX IDX_REPO_CUS_ID ON CIES_TRN_REPO_INFO (CUS_ID);
CREATE INDEX IDX_TASK_REF_ID ON CIES_TRN_TASK_INFO (REF_ID);
CREATE INDEX IDX_TASK_STATUS_CREATE_TIME
    ON CIES_TRN_TASK_INFO (TASK_STATUS, CREATE_TIME);
